env:
  global:
    - STORMPATH_API_KEY_ID=NV3TYA83GTW1W04MGCRJ5G9HX
    - STORMPATH_API_KEY_SECRET=1xEc3XZfteZm0TTAcsRFo32vEcee2MVlmOkjaIPcpmE
    - USERNAME_USER=user1
    - PASSWORD_USER=Password1
language: java
jdk:
  - oraclejdk8
after_success:
  - mvn sonar:sonar
